### PR TITLE
WIP: Adds Docs and Test

### PR DESCRIPTION
**Pull request by alanpeabody**
Initial code was developed/extracted from app with controller specs.

Intent of this PR is to bring tests and docs up to a state that the lib is ready for public feedback and consumption.

TODO:

- [x] README intro
- [x] Index action docs and tests
- [x] Show action docs and tests
- [x] Create action docs and tests
- [x] Update action docs and tests
- [x] Delete action docs and tests
- [ ] Filter tests and docs
- [ ] Sort tests and docs
- [x] Record(s) docs and tests

### CODE REVIEW

**Comment by rynam0** [comment]
This looks like it would surely lower the bar to entry for new apps.  Thanks for sharing!  Being a complete n00b to elixir/phoenix I've been working at consuming JSON API documents with relationships and this PR offered some great hints at how to go about it.  I could be completely wrong here (or going about saving many-to-many relationships in the wrong way) but it looks like the pattern matching here (https://github.com/AgilionApps/ja_resource/blob/master/lib/ja_resource.ex#L70) may fail when the incoming "data" property is an array.  I apologize for not being able to offer a test case at this time but I look forward to the day I am fluent enough in elixir to offer some real contributions. 

'''
"relationships" => %{"applications" => %{"data" => []}
'''

**Comment by alanpeabody** [comment]
Thanks for the feedback @rynam0. I do think it is probably wise to support arrays their, especially with many to many relationships coming in ecto.

**Comment by rynam0** [comment]
@alanpeabody: how might I take this for a test drive?  I thought using the following in my mix.ex file might work but it didn't:
```{:ja_resource, github: "AgilionApps/ja_resource", override: true}```

**Comment by rynam0** [comment]
Sorry. Long week... It helps when you run the correct mix task. :)

**Comment by alanpeabody** [comment]
Thanks for giving it a shot! I still have some out standing documentation, tests, and in particular install instructions so any feedback or difficulties you hit let me know.

**Comment by rynam0** [comment]
@alanpeabody: Fantastic work here!  The first obstacle I hit was wanting to add Scrivener pagination info to the top level "meta" property. I'm still not quite sure how to do so at this point but it looks like you may have an open issue that would address this.  The other thing I'm not clear on yet is how to do filters based on incoming parameters.  It looks like I may be able to utilize the records/2 function to accomplish this so I'll keep tinkering. Again, great work here and thanks for being my unknowing elixir mentor ;)

**Comment by alanpeabody** [comment]
Yeah, for pagination I would potentially like to make it super easy to add. I need to think through it a bit more, but on the serialization side the just passing the results of `MyApp.Repo.paginate/2` handles setting the meta for you. It is actually calling paginate with the correct params that needs to be added here.

Filters and Sorts are supported in master, but I have not documented or written tests for them yet because I think the API should probably change.

Currently the filter callbacks would look like:

```elixir
def filter("foo", query, value) do
  # apply foo filter to query (add a where or whatever)
end

def filter("bar", query, value) do
  # apply bar filter to query (add a where or whatever)
end

def filter(_, q, _), do: q
```

I don't think the argument order is quite right and I also think the conn should be an argument so you can filter based on conn state (eg, current user).

I also wanted to take a look at making this an optional integration: https://github.com/DockYard/inquisitor

**Pull request merged**
